package com.universe.auth.service;

import com.universe.auth.dto.request.*; import com.universe.auth.dto.response.*; import com.universe.global.exception.*; import com.universe.global.security.*; import com.universe.user.entity.User; import com.universe.user.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service @RequiredArgsConstructor
public class AuthService {
 private final UserRepository users; private final PasswordEncoder encoder; private final JwtTokenProvider jwt; private final TokenSessionService sessions;
 @Transactional public SignupResponse signup(SignupRequest r){ if(users.existsByEmail(r.getEmail())) throw new BusinessException(ErrorCode.DUPLICATE_EMAIL); User u=User.builder().email(r.getEmail()).password(encoder.encode(r.getPassword())).name(r.getName()).nickname(r.getNickname()).build(); users.save(u); return new SignupResponse(u.getId(),u.getEmail(),u.getNickname());}
 @Transactional(readOnly=true) public LoginResponse login(LoginRequest r){ User u=users.findByEmail(r.getEmail()).orElseThrow(()->new BusinessException(ErrorCode.INVALID_CREDENTIALS)); if(!encoder.matches(r.getPassword(),u.getPassword())) throw new BusinessException(ErrorCode.INVALID_CREDENTIALS); if(!u.getAccountStatus().name().equals("ACTIVE")) throw new BusinessException(ErrorCode.INACTIVE_ACCOUNT); return new LoginResponse(u.getId(),u.getEmail(),u.getNickname(),jwt.createAccessToken(u.getId(),u.getRole().name()),jwt.createRefreshToken(u.getId(),u.getRole().name()));}
 @Transactional(readOnly=true) public TokenResponse refresh(RefreshRequest r){ if(!jwt.isRefresh(r.getRefreshToken())) throw new BusinessException(ErrorCode.INVALID_REFRESH_TOKEN); var c=jwt.parse(r.getRefreshToken()); Long id=Long.valueOf(c.getSubject()); if(sessions.isInvalid(id,c.getIssuedAt().toInstant())) throw new BusinessException(ErrorCode.INVALID_REFRESH_TOKEN); User u=users.findById(id).orElseThrow(()->new BusinessException(ErrorCode.INVALID_REFRESH_TOKEN)); if(!u.getAccountStatus().name().equals("ACTIVE")) throw new BusinessException(ErrorCode.INACTIVE_ACCOUNT); return new TokenResponse(jwt.createAccessToken(id,u.getRole().name()),jwt.createRefreshToken(id,u.getRole().name()));}
 public void logout(){sessions.logout(CurrentUser.id());}
}
