package com.universe.auth.service;

import com.universe.auth.dto.request.*; import com.universe.auth.dto.response.*; import com.universe.global.exception.*; import com.universe.global.security.*; import com.universe.school.entity.School; import com.universe.school.entity.SchoolVerification; import com.universe.school.repository.SchoolVerificationRepository; import com.universe.school.service.SchoolEmailPolicy; import com.universe.trust.service.TrustScoreService; import com.universe.user.entity.User; import com.universe.user.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service @RequiredArgsConstructor
public class AuthService {
 private final UserRepository users; private final PasswordEncoder encoder; private final JwtTokenProvider jwt; private final TokenSessionService sessions; private final TrustScoreService trust; private final EmailVerificationService emailVerification; private final SchoolEmailPolicy schoolEmails; private final SchoolVerificationRepository verifications;
 @Transactional public SignupResponse signup(SignupRequest r){ String email=schoolEmails.normalize(r.getEmail()); if(users.existsByEmail(email)) throw new BusinessException(ErrorCode.DUPLICATE_EMAIL); School school=schoolEmails.resolveSchool(email); User u=User.builder().email(email).password(encoder.encode(r.getPassword())).name(r.getName().trim()).nickname(r.getNickname().trim()).department(r.getDepartment().trim()).build(); u.verifySchool(school); users.save(u); SchoolVerification v=SchoolVerification.builder().user(u).school(school).schoolEmail(email).build(); v.verify(); verifications.save(v); trust.initializeNewUser(u.getId()); emailVerification.consume(email); return new SignupResponse(u.getId(),u.getEmail(),u.getNickname());}
 @Transactional(readOnly=true) public LoginResponse login(LoginRequest r){ User u=users.findByEmail(r.getEmail()).orElseThrow(()->new BusinessException(ErrorCode.INVALID_CREDENTIALS)); if(!encoder.matches(r.getPassword(),u.getPassword())) throw new BusinessException(ErrorCode.INVALID_CREDENTIALS); if(!u.getAccountStatus().name().equals("ACTIVE")) throw new BusinessException(ErrorCode.INACTIVE_ACCOUNT); return new LoginResponse(u.getId(),u.getEmail(),u.getNickname(),jwt.createAccessToken(u.getId(),u.getRole().name()),jwt.createRefreshToken(u.getId(),u.getRole().name()));}
 @Transactional(readOnly=true) public TokenResponse refresh(RefreshRequest r){ Long id; try{if(!jwt.isRefresh(r.getRefreshToken()))throw new BusinessException(ErrorCode.INVALID_REFRESH_TOKEN); id=jwt.getUserId(r.getRefreshToken()); if(sessions.isInvalid(id,jwt.getIssuedAt(r.getRefreshToken())))throw new BusinessException(ErrorCode.INVALID_REFRESH_TOKEN);}catch(BusinessException e){throw new BusinessException(ErrorCode.INVALID_REFRESH_TOKEN);} User u=users.findById(id).orElseThrow(()->new BusinessException(ErrorCode.INVALID_REFRESH_TOKEN)); if(!u.getAccountStatus().name().equals("ACTIVE")) throw new BusinessException(ErrorCode.INACTIVE_ACCOUNT); return new TokenResponse(jwt.createAccessToken(id,u.getRole().name()),jwt.createRefreshToken(id,u.getRole().name()));}
 public void logout(){sessions.logout(CurrentUser.id());}
}
