package com.universe.community.service;
import com.universe.community.dto.request.*; import com.universe.community.dto.response.*; import com.universe.community.entity.*; import com.universe.community.repository.*; import com.universe.global.common.PageResponse; import com.universe.global.exception.*; import com.universe.global.security.CurrentUser; import com.universe.school.repository.SchoolRepository; import com.universe.user.repository.UserRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.PageRequest; import org.springframework.data.domain.Pageable; import org.springframework.data.domain.Sort; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.List;
@Service @RequiredArgsConstructor public class CommunityPostService {private final CommunityPostRepository posts;private final UserRepository users;private final SchoolRepository schools;private final HashtagRepository hashtags;private final PostHashtagRepository postHashtags;private final PostLikeRepository likes;
 @Transactional(readOnly=true) public PageResponse<CommunityPostListResponse> list(String category,String keyword,String hashtag,String sort,int page,int size){var u=currentUser();Pageable p=PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100));var result=posts.search(u.getSchool().getId(),category,keyword,hashtag,sort,p);return new PageResponse<>(result.map(this::toList));}
 @Transactional public CommunityPostResponse create(PostCreateRequest r){var u=currentUser();if(u.getSchool()==null||!Boolean.TRUE.equals(u.getSchoolVerified()))throw new BusinessException(ErrorCode.FORBIDDEN);var post=posts.save(CommunityPost.builder().user(u).school(u.getSchool()).category(r.getCategory()).title(r.getTitle()).content(r.getContent()).isAnonymous(r.getIsAnonymous()).build());saveHashtags(post,r.getHashtags());return toResponse(post);}
 @Transactional public CommunityPostDetailResponse detail(Long id){var p=posts.findByIdAndStatus(id,PostStatus.ACTIVE).orElseThrow(()->new BusinessException(ErrorCode.POST_NOT_FOUND));if(!sameSchool(p))throw new BusinessException(ErrorCode.CROSS_SCHOOL_ACCESS);p.increaseViewCount();return toDetail(p);}
 @Transactional public CommunityPostResponse update(Long id,PostUpdateRequest r){var p=ownedPost(id);p.updateContent(r.getTitle(),r.getContent(),r.getCategory());postHashtags.deleteByPostId(p.getId());saveHashtags(p,r.getHashtags());return toResponse(p);}
 @Transactional public void delete(Long id){ownedPost(id).deletePost();}
 private CommunityPost ownedPost(Long id){var p=posts.findByIdAndStatus(id,PostStatus.ACTIVE).orElseThrow(()->new BusinessException(ErrorCode.POST_NOT_FOUND));if(!p.getUser().getId().equals(CurrentUser.id()))throw new BusinessException(ErrorCode.FORBIDDEN);return p;}
 private boolean sameSchool(CommunityPost p){var u=currentUser();return u.getSchool()!=null&&u.getSchool().getId().equals(p.getSchool().getId());}
 private com.universe.user.entity.User currentUser(){return users.findById(CurrentUser.id()).orElseThrow(()->new BusinessException(ErrorCode.UNAUTHORIZED));}
 private void saveHashtags(CommunityPost p,List<String> names){if(names==null)return;names.stream().filter(n->n!=null&&!n.isBlank()).map(String::trim).distinct().forEach(n->{var h=hashtags.findByName(n).orElseGet(()->hashtags.save(Hashtag.builder().name(n).build()));postHashtags.save(PostHashtag.builder().post(p).hashtag(h).build());});}
 private CommunityPostResponse toResponse(CommunityPost p){return new CommunityPostResponse(p.getId(),p.getCategory().name(),p.getTitle(),p.getContent(),Boolean.TRUE.equals(p.getIsAnonymous()),p.getUser().getId(),p.getSchool().getId());}
 private CommunityPostListResponse toList(CommunityPost p){return new CommunityPostListResponse(p.getId(),p.getCategory().name(),p.getTitle(),p.getContent().length()>100?p.getContent().substring(0,100):p.getContent(),Boolean.TRUE.equals(p.getIsAnonymous()),Boolean.TRUE.equals(p.getIsAnonymous())?null:p.getUser().getId(),Boolean.TRUE.equals(p.getIsAnonymous())?"익명":p.getUser().getNickname(),p.getViewCount(),likes.countByPostId(p.getId()),p.getCreatedAt(),postHashtags.findByPostId(p.getId()).stream().map(x->x.getHashtag().getName()).toList());}
 private CommunityPostDetailResponse toDetail(CommunityPost p){return new CommunityPostDetailResponse(p.getId(),p.getCategory().name(),p.getTitle(),p.getContent(),Boolean.TRUE.equals(p.getIsAnonymous()),Boolean.TRUE.equals(p.getIsAnonymous())?null:p.getUser().getId(),Boolean.TRUE.equals(p.getIsAnonymous())?"익명":p.getUser().getNickname(),p.getSchool().getId(),p.getViewCount(),likes.countByPostId(p.getId()),p.getCreatedAt(),p.getUpdatedAt(),postHashtags.findByPostId(p.getId()).stream().map(x->x.getHashtag().getName()).toList());}
}
